version: '3'

services:
  php:
    build:
      context: portfolio_mvc
    container_name: Portfolio_MVC
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - ./portfolio_mvc:/var/www/html
    ports:
      - "${PHP_PORT}:80"
    networks:
      - app-network
    restart: unless-stopped

  react:
    build:
      context: portfolio_react
    container_name: Portfolio_React
    volumes:
      - ./portfolio_react:/app
    ports:
      - "${REACT_PORT}:3000"
    networks:
      - app-network
    depends_on:
      - php
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: Portfolio_mysql
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge